% VSIS-Aufgabenblatt
%
% LaTeX-Klasse zur Erstellung von Aufgabenblaettern inkl. optionaler Musterloesung im VSIS-Stil.
%
% Entworfen von Wolfram Wingerath auf Grundlage eines existierenden Designs von Kristof Hamann

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{gdb-aufgabenblatt}[2009/11/08 v1.0 VSIS-Aufgabenblaetter]

\LoadClass{vsis-aufgabenblatt}


\newcommand{\Gruppe}{*Teilnehmernamen*}


\renewcommand{\Vorlesung}{Grundlagen von Datenbanken}
\renewcommand{\Semester}{WS 2013/14}
\renewcommand{\Punktezahl}{40}


\renewcommand{\PunktezahlTitel}{Gruppe}
\renewcommand{\Punktezahl}{\Gruppe}